version: '3.3'
services:
  gitea:
    image: gitea/gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=sgbd-db-mysql-1:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=usr_git
      - GITEA__database__PASSWD=to_replace
    networks:
      - databases
      - management_web
    volumes:
      - /srv/data/gitea/git_data:/data
      - /srv/data/gitea/git_vardata:/var/lib/gitea   
      - /srv/conf/gitea:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2222:2222
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`to_replace`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.http.routers.gitea.service=gitea
      - traefik.http.routers.gitea.tls.certresolver=lets-encrypt     
networks:
  management_web:
     external: true
  databases:
     external: true